### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SomeSnm** [catboost/benchmarks#1]
Hello! 

The link to comparison description on Benchmarks page is broken. 

Here is the link:
https://github.com/yandexdataschool/catboost_research/blob/master/experiments/comparison_description.pdf

**Comment by grossws** [comment]
Correct link is https://github.com/catboost/benchmarks/blob/master/comparison_description.pdf

**Comment by nikitxskv** [comment]
Hello!

Thank you for report, I've fixed it in #4.
