### ISSUE TITLE
Bug in experiments.py

### ISSUE THREAD

**Issue by liuyang21cn** [catboost/benchmarks#11]
File "training_speed/experiments.py", line 126
    return ''.join(map(lambda (key, value): '{}[{}]'.format(key, str(value)), params.items()))

SyntaxError: invalid syntax

I'm using python 3 and it gave me this warning on the use of lmabda.

**Comment by nottatdat** [comment]
Please take a look at this PR https://github.com/catboost/benchmarks/pull/10 and modify your code accordingly (as it have not been merged).

**Comment by annaveronika** [comment]
The PR is merged, thank you very much for your contribution!
